sudo: false
language: cpp
cache:
  ccache: true
  directories:
  - "/home/travis/toolchain"
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - g++-8
        - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"
  - os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - clang-6.0
        - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"
  - os: linux
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"
before_install:
- eval $MATRIX_EVAL
install:
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true
  ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm || travis_retry
  brew upgrade llvm ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install openssl || travis_retry
  brew upgrade openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew link --force openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl
  /usr/local/include ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"
  ; fi
script:
- eval $MATRIX_EVAL
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi
before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="Catalystd miner zedwallet catalyst-service zedwallet-beta cryptotest wallet-api"
- "${STRIP} ${TARGETS}"
- rm -rf catalyst-${TRAVIS_TAG}
- mkdir catalyst-${TRAVIS_TAG}
- cp ${TARGETS} catalyst-${TRAVIS_TAG}/
- cp ../../LICENSE catalyst-${TRAVIS_TAG}/
- tar cvfz catalyst-${TRAVIS_TAG}-${LABEL}.tar.gz catalyst-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp catalyst-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..
deploy:
  provider: releases
  api_key:
    secure: Bvv6NglewXXOg/S2iJ5+yvd5dT2ygDJrxpA2kjhLk79kUGju9RZXaTq5NPenIru/FBDfVj97VIud2cfRQu17Z2lMfP7EvAJkGCcgLgH5BvNTgOLGY753wLVQwkR4zfM9WujAYUs1V6fvkDpdqObqo8mbinxadLmMr1cDBgC107FEBnvRBVKkG/6MNIH84jq4WMisV8luBw0xTH36y17NFj6ofjlJ7EKPWXXzx3DGs+E/vVVGNjdcZz4S4cMzcsPE/ruklGfV3MiP5Z7c8dYmOe3eLX26zQrXcJ7agMfT4sCmtiF8HzP5cwbjJqsc7I/2xJXQXuyxA7B/C0HTF84FvpPAm+K/x1rL88/EwcqY9g9v5ip5fMouqJ2DAx029tEcOZdTVwV1WBkcckLxWUcTdlmaM1OavXX3CBBC0V4SdcFyPz0DgoKb/lfkCuqVGZhJ/sGoIeyWrfgU4ZyszCl73bHFO+OBBxda66E9maUpIZFhoI8oW3kYlPFq+NWqqZysxR7wCqeQ5a4O90PDrAixPe8jPDV74EzkbxE3PhQPT9EFGGDlt7QEuPYNS3TeH4i7jMBx6qVwlA4WZtdPwUtVWdqoqHiX/YQmy+BwXFP1oL3C6njhD6iGT8AK0tqS42HZPon4B82M+nlhy+3Gq6Ywzp14BazzuLsaocPoJad/l/c=
  file: ''
  on:
    repo: catalystdevelopment/catalyst
    branch: development
